name: Feature Building

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          brew install automake
          make VERSION="${GITHUB_SHA::7}" debug
          make debug-dmg
          shasum -a 256 build/Debug/ShadowsocksX-NG.dmg > build/Debug/ShadowsocksX-NG.dmg.checksum

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ShadowsocksX-NG
          path: |
            build/Debug/ShadowsocksX-NG.dmg
            build/Debug/ShadowsocksX-NG.dmg.checksum
