name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
    - name: Run unit test
      run: |
        set -o pipefail && xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
    - uses: sersoft-gmbh/xcodebuild-action@v2
      name: build
      with:
       project: ShadowsocksX-NG.xcodeproj
       scheme: ShadowsocksX-NG
       destination: platform=macOS
       action: build
