name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.app
    - name: Install Dependencies
      run: |
        pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'
        additional_lint_params: --private
    - name: Run unit test
      run: |
        set -o pipefail && xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
    - uses: sersoft-gmbh/xcodebuild-action@v1
      name: build
      with:
       project: ShadowsocksX-NG.xcodeproj
       scheme: ShadowsocksX-NG
       destination: platform=macOS
       action: build
