name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run unit test
      run: |
        set -o pipefail && xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
    - uses: sersoft-gmbh/xcodebuild-action@v1
      name: build
      with:
       project: ShadowsocksX-NG.xcodeproj
       scheme: ShadowsocksX-NG
       destination: platform=macOS
       action: build
