name: Release Building

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          brew install automake
          make VERSION="${GITHUB_REF_NAME}" release
          make release-dmg 
          shasum -a 256 build/Release/ShadowsocksX-NG.dmg > build/Release/ShadowsocksX-NG.dmg.checksum

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ShadowsocksX-NG
          path: |
            build/Release/ShadowsocksX-NG.dmg
            build/Release/ShadowsocksX-NG.dmg.checksum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            build/Release/ShadowsocksX-NG.dmg
            build/Release/ShadowsocksX-NG.dmg.checksum
